# Generated by Django 3.1.2 on 2020-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('starring', models.CharField(max_length=100)),
                ('release', models.DateField()),
                ('director', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=10)),
                ('age_rating', models.CharField(max_length=3)),
            ],
        ),
    ]
