# Generated by Django 3.1.3 on 2021-02-22 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('starring', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=4)),
                ('director', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=10)),
                ('age_rating', models.CharField(max_length=3)),
                ('trailer', models.CharField(max_length=200)),
                ('genre', models.ManyToManyField(related_name='genres', to='genres.Genre')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
