# Generated by Django 3.1.2 on 2020-10-24 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
