# Generated by Django 3.1.2 on 2020-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
